# Generated by Django 2.0 on 2020-12-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='url',
            field=models.CharField(default='default_url', max_length=40),
            preserve_default=False,
        ),
    ]
